export PATH="$HOME/.config/emacs/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
alias vim='nvim'
alias ls='eza -1 --color=auto'
alias cd='z'

fastfetch
