background            #05070a
foreground            #d1d7e0
cursor                #ffffff
selection_background  #2e3c51
selection_foreground  #ffffff


color0  #05070a
color8  #1e222a

color1  #7d8691
color9  #949fb0

color2  #b8bfc6
color10 #ced5db

color3  #e0e0e0
color11 #ffffff

color4  #5f697d
color12 #8693ab

color5  #8a8a8a
color13 #a1a1a1

color6  #a3b1b5
color14 #c1d1d6

color7  #d1d7e0
color15 #ffffff
