# Inspired by jzhao.xyz

background            #02040a
foreground            #d8dee9
cursor                #d8dee9
selection_background  #101a2d
selection_foreground  #ffffff


color0 #02040a
color8 #101a2d

color4 #4c566a
color12 #81a1c1
color6 #5e81ac
color14 #88c0d0

color7  #b4bece
color15 #d8dee9

color1 #3b4252
color9 #4c566a
color2 #3b4252
color10 #4c566a
color3 #3b4252
color11 #434c5e
color5 #3b4252
color13 #4c566a

active_border_color   #101a2d
inactive_border_color #02040a
url_color             #81a1c1
url_style             straight
