#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

default=(
  padding_left=3
  padding_right=3
  icon.font="CaskaydiaCove Nerd Font:Regular:14.0"
  label.font="CaskaydiaCove Nerd Font:Regular:14.0"
  icon.color=0xffc9c7cd
  label.color=0xffc9c7cd
  icon.padding_left=7
  icon.padding_right=7
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change
LABELS=("1" "2" "3" "4" "5" "6" "7" "8" "9")

for sid in $(aerospace list-workspaces --all); do
  label="${LABELS[$INDEX]}"

  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=0x44ffffff \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=off \
    icon.padding_left=3 \
    icon.padding_right=3 \
    label.padding_left=3 \
    label.padding_right=3 \
    label="$label" \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"

  INDEX=$((INDEX + 1))
done

sketchybar --add item chevron left \
  --set chevron icon='' label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  icon.padding_left=8 \
  icon.padding_right=6 \
  label.padding_left=6 \
  label.padding_right=8

sketchybar --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  icon.padding_left=8 \
  icon.padding_right=6 \
  label.padding_left=6 \
  label.padding_right=8 \
  --subscribe volume volume_change

sketchybar --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  icon.padding_left=8 \
  icon.padding_right=6 \
  label.padding_left=6 \
  label.padding_right=8 \
  --subscribe battery system_woke power_source_change

sketchybar --update
